LR-6: Language Files
Rytrox/LuckyRace pull request #5
Opened 2022-08-07 16:47 UTC by Sether701

2022-08-07 19:55 UTC, Timeout-Timo commented
Unittests?

2022-08-07 20:01 UTC, Sether701 commented
war klar, dass das von dir kommt, Timo

> Unittests?

2022-08-07 20:02 UTC, Sether701 commented
Kannst trotzdem darüber hinaus mal den Code anschauen, der da ist

2022-08-07 20:02 UTC, Sether701 commented
Vor allem darf ich jetzt Unit-Tests für etwas schreiben, dass du nachher sowieso wieder ganz anders haben möchtest, weil du irgendeine tolle Idee hast...

2022-08-07 20:03 UTC, Sether701 commented
Ich schreib die Tests morgen :d

2022-08-07 20:03 UTC, Asedem commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +    private final LuckyRace main;
Du hast hier eine Variable, welche du nie benutzt.

2022-08-07 20:08 UTC, Timeout-Timo requested changes

2022-08-07 20:08 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +    }
Wird das hier nicht irgendwann zu voll sein?

Ist ja schön und gut, aber ich glaube das sollten wir doch auslagern in ne separate Datei

2022-08-07 20:08 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +        }
Bitte hier die java.nio.Path API nutzen

2022-08-07 20:11 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +    }
why? Dann wird eine andere Datei lang. Bringt doch nichts

2022-08-07 20:11 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +        }
bitte begründen warum?

2022-08-07 20:33 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +        }
Um Betriebsystemunabhänhigkeit zu gewährleisten

2022-08-07 20:34 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +    }
Dann müssen wir uns hier was anderes überlegen. Ich hab halt die Sorge, dass das später unleserlich wird

2022-08-08 04:57 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +        }
Ich wusste gar nicht, dass das ein Ding ist

2022-08-08 05:00 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/util/MessageProvider.java
> +    }
Ja... Ich weiß ja nicht wie du dir das vorstellst. Wenn du auf die Nachrichten zugreifen willst, musst du zwangsläufig irgendwie einen Pfad angeben. Du könntest den Pfad jedes mal als String schreiben, dann sparst du dir das Enum, aber dann wirds halt hart unübersichtlich und refactoring wird auch bled. Das einzige was man noch machen könnte, wäre das Enum in viele kleinere Enums aufzuteilen, aber ob es das besser macht, weiß ich auch net.

2022-08-08 08:48 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/LuckyRace.java
> +
```suggestion
@NotNull
```

2022-08-08 08:48 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/message/MessageProvider.java
> +    public String getMessage(Message message) {
```suggestion
     */
    @NotNull
    public String getMessage(Message message) {
```

2022-08-08 08:48 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/message/MessageProvider.java
> +        public Path getConfigPath() {
```suggestion
        @NotNull
        public Path getConfigPath() {
```

2022-08-08 08:48 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/util/message/MessageProvider.java
> +        public static Optional<Language> findLanguage(String isoCode) {
```suggestion
        @NotNull
        public static Optional<Language> findLanguage(String isoCode) {
```

2022-08-08 09:02 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/util/message/MessageProvider.java
> +        public Path getConfigPath() {
von mir aus

2022-08-09 08:14 UTC, Timeout-Timo approved these changes

2022-08-09 08:14 UTC, merged