LR-7: Allgemeine Informationen bereitstellen
Rytrox/LuckyRace pull request #8
Opened 2022-08-10 16:56 UTC by Sether701

2022-08-10 16:56 UTC, Sether701 commented
![grafik](https://user-images.githubusercontent.com/33812610/183971065-eb6fe64b-c90a-45f7-846d-6a3002d80b9a.png)

2022-08-10 18:47 UTC, Sether701 commented
update
![grafik](https://user-images.githubusercontent.com/33812610/183992946-764171e4-747a-4ea8-a9f8-d5b8124b77aa.png)

2022-08-10 19:13 UTC, Timeout-Timo requested changes
Vielleicht sollten wir dieses About einmal auslagern, das müllt die Main eventuell was zu.

2022-08-10 19:13 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/LuckyRace.java
> +        } catch (Exception ignored) {}
try catch mit Exception ist böse...

2022-08-10 19:20 UTC, Sether701 commented
TODO: Tests

2022-08-11 16:23 UTC, Timeout-Timo approved these changes

2022-08-11 16:24 UTC, merged