LR-9: PhaseHandler
Rytrox/LuckyRace pull request #9
Opened 2022-08-16 14:46 UTC by Asedem

2022-08-16 16:38 UTC, Sether701 commented on src/test/java/de/rytrox/luckyrace/phase/PhaseHandlerTest.java
> +    }
macht der Test so Sinn? Sieht soweit eigentlich so ziemlich genauso aus, wie der vorherige Test

2022-08-16 16:39 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/phase/phases/EndPhase.java
> +        return new EndPhase(main);
Nach der Endphase kommt eine neue Endphase?

2022-08-16 16:40 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/phase/PhaseHandler.java
> +     * get the current chase
Du meinst wohl 'get the current phase' oder?

2022-08-16 16:40 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/phase/PhaseHandler.java
> +     * change the chase to the next or the setup phase
hier nochmal 'chase' statt 'phase'

2022-08-16 16:46 UTC, Asedem commented on src/test/java/de/rytrox/luckyrace/phase/PhaseHandlerTest.java
> +    }
Ja, da dieser testet, ob zu der SetupPhase gewechselt wird, wenn man mit changePhase(true) die phase wechselt. Und im anschluss wird dann noch gesetet, ob man von der SetupPhase wieder in die LobbyPhase geschickt wird.

2022-08-16 16:49 UTC, Asedem commented on src/main/java/de/rytrox/luckyrace/phase/phases/EndPhase.java
> +        return new EndPhase(main);
Kommt darauf an, was wir gerne wollen. Wollen wir, dass nach der EndPhase der Server neu gestartet wir, oder wollen wir dann zur Lobby Phase zurück springen?

Ich weiß halt nicht, was ich sonst da rein schreiben sollte, wenn wir den Server neu starten möchten,

2022-08-16 17:13 UTC, Sether701 commented on src/test/java/de/rytrox/luckyrace/phase/PhaseHandlerTest.java
> +    }
Dann fehlt mir aber noch der Test, dass die Phase tatsächlich gewechselt wird, wenn man nicht im Setup ist

2022-08-16 17:13 UTC, Sether701 commented on src/main/java/de/rytrox/luckyrace/phase/phases/EndPhase.java
> +        return new EndPhase(main);
ja, darum gehts mir aber gar nicht. Mir gehts nur darum, warum du da ne neue Instanz erstellst

2022-08-16 17:38 UTC, Timeout-Timo requested changes
Zudem möchte ich gerne die Phasen-Klassen anders auslagern.

Also LobbyPhase ins Paket "lobby", wo auch alle anderen Klassen und Listener landen und alle anderen Phasen auch. Das fände ich besser und auch übersichtlicher

2022-08-16 20:16 UTC, Timeout-Timo commented on src/main/java/de/rytrox/luckyrace/phase/PhaseHandler.java
> +    }
Der Parameter widerspricht auch dem Strategy-Pattern, das du hier benutzt. Das ist eigentlich nicht Sinn und Zweck des Ganzen. Hier wird das Pattern nochmal erklärt

https://javabeginners.de/Design_Patterns/Strategy_-Pattern.php

2022-08-17 16:31 UTC, Timeout-Timo approved these changes

2022-08-17 16:35 UTC, merged